# Reference: https://github.com/i3/i3/blob/next/etc/config

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

[mode.main.binding]
    alt-p = '''exec-and-forget aerospace move-node-to-monitor --focus-follows-window --wrap-around next && aerospace fullscreen'''
    alt-f = '''fullscreen'''

    alt-j = '''exec-and-forget osascript -e '
    tell application "Google Chrome"
        activate
    end tell'
    '''
    alt-h = '''exec-and-forget osascript -e '
    tell application "obsidian"
        activate
    end tell'
    '''

    alt-t = '''exec-and-forget osascript -e '
    tell application "Ghostty"
        activate
    end tell'
    '''

    alt-b = '''exec-and-forget osascript -e '
    tell application "Slack"
        activate
    end tell'
    '''
    
    alt-g = '''exec-and-forget osascript -e '
    tell application "Spotify"
        activate
    end tell'
    '''

    alt-m = '''exec-and-forget osascript -e '
    tell application "Mail"
        activate
    end tell'
    '''

    alt-i = '''exec-and-forget osascript -e '
    tell application "IntelliJ IDEA"
        activate
    end tell'
    '''

    alt-d = '''exec-and-forget osascript -e '
    tell application "Discord"
        activate
    end tell'
    '''

    alt-k = '''exec-and-forget osascript -e '
    tell application "Calendar"
        activate
    end tell'
    '''
[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'md.obsidian'
run = ['layout floating']

